#! /bin/bash

newparams=()
for param; do
    if [[ "$param" == -* ]]; then
        newparams+=("$param")
    elif test -z "$autoproj_path"; then
        autoproj_path=$param
    elif test -z "$debugger"; then
        debugger=$param
    fi
done

exec "$autoproj_path" exec "$debugger" "${newparams[@]}"
